name: github_starred_repos
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2
  # Provider
  provider: ^5.0.0
  # Fonts
  google_fonts: ^2.1.0
  # Http
  http: ^0.13.3
  # Spinner
  flutter_spinkit: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true